services:
  dotnet-backend:
    build:
      context: ../../apps/TrafficClaimIntegratorAPI
      dockerfile: ../../infra/shared/TrafficClaimIntegratorAPI.Dockerfile
    ports:
      - "5001:8080"
    container_name: dotnet-backend
    volumes:
      - ../../apps/TrafficClaimIntegratorAPI:/app/src
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_EnableDiagnostics=1
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=TrafficDb;Username=postgres;Password=postgres
    depends_on:
      - db

  db:
    image: postgres:16.8
    restart: always
    container_name: dotnet-db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=TrafficDb
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
      - ./db/init_testdb.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: dotnet-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - "5050:80"
    depends_on:
      - db
